REM SET IF NOT ALREADY PRESENT
REM SET GOROOT=D:/WORK/IT/GO/go1.9.1
REM SET PATH=%PATH%;%GOROOT%/bin

REM SET IF NOT ALREADY PRESENT
REM SET GOPATH=D:\WORK\IT\PROJECTS_WS\GO_WS
REM SET PATH=%PATH%;%GOPATH%/bin

IF "%S_VERSION%" == ""  (SET S_VERSION=RAS)