language: go

go:
  - 1.7
  - tip
gobuild_args: -ldflags "-X main.Version $(cat $TRAVIS_BUILD_DIR) -X GitCommit $(git rev-parse --short HEAD) -X GitBranch $(git rev-parse --abbrev-ref HEAD)"
install:
  - export GOPATH="${TRAVIS_BUILD_DIR}"
