#!/bin/sh

dir="$(dirname $0)"
cwd=$(cd $dir; pwd)
VERSION=${project.version}
GROUP=com.vsct.dt.strowgr
ARTIFACT=sidekick
if [[ $VERSION == *-SNAPSHOT ]];then
    REPO=dt-snapshots
else
    REPO=dt-releases
fi

curl -L http://nexus/service/local/artifact/maven/redirect?r=$REPO\&g=$GROUP\&a=$ARTIFACT\&v=$VERSION\&p=tar.gz\&c=dist | tar xzvC ./

echo "update link sidekick -> sidekick-linux-amd64-$VERSION/sidekick"
chmod +x sidekick-linux-amd64-$VERSION/sidekick
rm sidekick
ln -s sidekick-linux-amd64-$VERSION/sidekick sidekick

echo "restart"
$cwd/RESTART 2>&1
echo "restarted"